volumes:
  pg_data:
  static:
  media:
  redoc:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: menastasiia/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
      - redoc:/app/api/docs/
  frontend:
    env_file: .env
    image: menastasiia/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: menastasiia/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
      - db
    ports:
      - 9090:80
    volumes:
      - static:/staticfiles/
      - media:/app/media/
      - redoc:/usr/share/nginx/html/api/docs/
