# Generated by Django 3.2.3 on 2025-07-07 08:13

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать только английские буквы, цифры или символы "@", ".", "_", "+", "-".', regex='^[\\w.@+-]+$'), api.validators.validate_username], verbose_name='Логин'),
        ),
    ]
