# Generated by Django 3.2.3 on 2025-07-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-id'], 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
